export enum EnumCacheUerRoutes {
  GET_ALL_NO_USER_USER = 'GET_ALL_NO_USER_USER',
  GET_ALL_USER = 'GET_ALL_USER',
  GET_PUBLIC_USER_BY_ID = 'GET_PUBLIC_USER_BY_ID',
  GET_USER_BY_ID = 'GET_USER_BY_ID',
}
