export enum EnumCacheEventRoutes {
  GET_ALL_PUBLIC_EVENTS = 'GET_ALL_PUBLIC_EVENTS',
  GET_ALL_EVENTS = 'GET_ALL_EVENTS',
  GET_PUBLIC_EVENTS_BY_ID = 'GET_PUBLIC_EVENTS_BY_ID',
  GET_EVENTS_BY_ID = 'GET_EVENTS_BY_ID',
}
