version: '3.9'

services:
  nx-app-base:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - application:/app
      - mono-node-modules:/app/node_modules
      - /app/node_modules/argon2/

