version: '3.9'

services:
  # Server app
  server:
    container_name: final-project-server
    volumes:
      - application-server:/usr/src/app
      - mono-node-modules:/usr/src/app/node_modules
      - final-app-upload-files:/usr/src/app/assets
    build:
      dockerfile: ./apps/server/Dockerfile
      target: prod
      context: .
    env_file:
      - ./apps/server/.env
    stdin_open: true
    tty: true
    ports:
      - "4300:4300"
    expose:
      - 4300
    networks:
      - project-network
      - final-project-common-network
  #    command: npm run server


  # React app
  web:
    container_name: final-project-web
    volumes:
      - application-web:/usr/src/app
      - mono-node-modules:/usr/src/app/node_modules
    build:
      dockerfile: ./apps/web/Dockerfile
      target: prod
      context: .
    stdin_open: true
    tty: true
    env_file:
      - ./apps/web/.env
#    environment:
#      NX_SOCKET_HOST: ${NX_SOCKET_HOST}
    ports:
      - "4200:4200"
    expose:
      - 4200
    networks:
      - project-network
      - final-project-common-network
    depends_on:
      - server
    links:
      - server

volumes:
  mono-node-modules: null
  final-app-upload-files:
  application-web:
  application-server:


networks:
  project-network:
  final-project-common-network:
    external: true



