version: '3.9'

services:
  final-project-redis:
    image: 'redis:alpine'
    container_name: 'final-project-redis'
    restart: always
    command: ["redis-server", "/etc/redis/redis.conf"]
    ports:
      - '6378:6379'
    networks:
      - redis-network
    volumes:
      - sport-redis-data:/data
      - ./redis.conf:/etc/redis/redis.conf

  redis-commander:
    image: 'ghcr.io/joeferner/redis-commander:latest'
    container_name: 'final-project-redis-commander'
    environment:
      - REDIS_HOST=final-project-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=Qjd#R7bBnWH7
      - HTTP_USER=root
      - HTTP_PASSWORD=root
    ports:
      - '8082:8081'
    restart: always
    networks:
      - redis-network
    depends_on:
      - final-project-redis

networks:
  redis-network:
    driver: bridge

volumes:
  sport-redis-data:
