version: '3.9'

services:
  # Server app
  server:
    container_name: final-project-server
    volumes:
      - application-server:/usr/src/app
      - mono-node-modules:/usr/src/app/node_modules
      - final-app-upload-files:/usr/src/app/assets
    build:
      dockerfile: ./apps/server/Dockerfile
      target: prod
      context: .
    env_file:
      - ./apps/server/.env
    stdin_open: true
    tty: true
    ports:
      - "4300:4300"
      - "465:465"
    expose:
      - 4300
    networks:
      - project-network
      - final-project-common-network
    depends_on:
      - redis

  # React app
  web:
    container_name: final-project-web
    volumes:
      - application-web:/usr/src/app
      - web-node-modules:/usr/src/app/node_modules
    build:
      dockerfile: ./apps/web/Dockerfile
      target: prod
      context: .
    stdin_open: true
    tty: true
    env_file:
     - ./apps/web/.env
    ports:
      - "4200:4200"
    expose:
      - 4200
    networks:
      - project-network
      - final-project-common-network
    depends_on:
      - server
    links:
      - server

  final-project-redis:
    image: 'redis:alpine'
    container_name: final-project-redis
    restart: always
    env_file:
      - ./apps/server/.env
    command: ["redis-server", "/etc/redis/redis.conf"]
    ports:
      - '6378:6379'
    networks:
      - project-network
      - final-project-common-network
    volumes:
      - sport-redis-data:/data
      - ./redis.conf:/etc/redis/redis.conf

  redis-commander:
    container_name: 'final-project-redis-commander'
    image: 'ghcr.io/joeferner/redis-commander:latest'
    environment:
      - REDIS_HOST=final-project-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=Qjd#R7bBnWH7
      - HTTP_USER=root
      - HTTP_PASSWORD=root
    ports:
      - '8082:8081'
    restart: always
    networks:
      - project-network
      - final-project-common-network
    depends_on:
      - redis

volumes:
  mono-node-modules: null
  web-node-modules: null
  final-app-upload-files:
  application-web:
  application-server:
  sport-redis-data:


networks:
  project-network:
    driver: bridge
  final-project-common-network:
    external: true



