version: '3.9'

services:
  # React app
  web:
    container_name: final-project-web
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    build:
      dockerfile: ./apps/web/Dockerfile
      target: develop
      context: .
    command: npm run front:docker
    stdin_open: true
    tty: true
    env_file:
      - ./apps/web/.env
    ports:
      - "4202:4200"
    networks:
      - project-network
      - final-project-common-network
    depends_on:
      - server
    links:
      - server

  # Server app
  server:
    container_name: final-project-server
    extends:
        file: docker-compose.base.yml
        service: nx-app-base
    build:
      dockerfile: ./apps/server/Dockerfile
      target: prod
      context: .
    env_file:
      - ./apps/server/.env
    stdin_open: true
    tty: true
    ports:
      - "4300:4300"
#    expose:
#      - 4300
    networks:
      - project-network
      - final-project-common-network
    command: npm run server


volumes:
  mono-node-modules: null
  application:

networks:
  project-network:
  final-project-common-network:
    external: true



