version: '3.9'

services:
  redis:
    image: 'redis:alpine'
    container_name: 'redis'
    restart: always
    command: ["redis-server", "/etc/redis/redis.conf"]
    ports:
      - '6379:6379'
    networks:
      - redis-network
    volumes:
      - sport-redis-data:/data
      - ./redis.conf:/etc/redis/redis.conf

  redis-commander:
    container_name: 'redis-commander'
    image: 'ghcr.io/joeferner/redis-commander:latest'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=Qjd#R7bBnWH7
      - HTTP_USER=root
      - HTTP_PASSWORD=root
    ports:
      - '8081:8081'
    restart: always
    networks:
      - redis-network
    depends_on:
      - redis

networks:
  redis-network:
    driver: bridge

volumes:
  sport-redis-data:
