version: '3.9'

services:
  redis:
    image: 'redis:alpine'
    container_name: 'redis'
    restart: always
    ports:
      - '6379:6379'
    networks:
      - redis-network
    volumes:
      - sport-redis-data:/data

  redis-commander:
    container_name: 'redis-commander'
    image: 'ghcr.io/joeferner/redis-commander:latest'
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8081:8081'
    restart: always
    networks:
      - redis-network
    depends_on:
      - redis

networks:
  redis-network:
    driver: bridge

volumes:
  sport-redis-data:
